### ISSUE TITLE
A proper collide! function

### ISSUE THREAD

**Issue by kavir1698** [JuliaDynamics/Agents.jl#149]
A function to calculate the velocity of two objects after colliding with each other.

**Comment by Datseris** [comment]
I assume with this issue that you mean "agents exchange their velocity", which I don't see why it should be implemented as a function since it is as trivials as `a1.vel, a2.vel = a2.vel, a1.vel`.

If you _don't_ mean that, then we have a problem. First of all, this can only be done if both agents are spheres, because only then there are analytic formulas on how to "find the collision". For ellipsoids, I only know formulas for 2D not 3D.

Even if you assume spheres, in my eyes, this is something exceptionally difficult to do properly. There is a reason that there are two Julia packages **exclusively** for sphere collisions: DynamicalBilliards.jl and HardSphereDynamics.jl. 

It is very hard to get the collision correctly and accurate. To demonstrate, I will simply ask you to define what you mean "colliding with each other". For me, it means to extrapolate the trajectories of all agents in the system, find the collision points, move the agents to the collision points. If you did everything accurately, then you will have spheres that are tangential to each other. Then, get the tanget vectors properly by taking into account the sphere centers. Then, calculate the velocities after collision (which mean reflection with tangent plane).

All of this seems too much don't you think? And it is also implemented by HardSphereDynamics.jl.

In addition, all of this is impossible for agents that do not move in straight lines, which is what `update_vel!` targets. So what did you have in mind when you opened the issue?

**Comment by kavir1698** [comment]
Oh, I didn't know that. I thought there were straightforward analytical formulas. I imagine it would be even more difficult with multiple objects colliding. I close this issue then.

**Comment by Datseris** [comment]
I had in mind that we could leverage `HardSphereDynamics` to make a new type of `Space` in agents that represents the agents exclusively as hard spheres (billiard balls). 

Then, the function collide would come naturally out of the dynamics of the billiards. But in my eyes this is a low priority simply because I feel a general agent based model doesn't really benefit too much from having such accuracy for the sphere dynamics. But if you think otherwise let me know. 

I will open an issue soon describing the hardsphere space.

**Comment by kavir1698** [comment]
Thank you. I also don't see much priority here.
