### ISSUE TITLE
No field min_to_be_happy on Schelling model

### ISSUE THREAD

**Issue by sbacelar** [JuliaDynamics/Agents.jl#216]
When I do `step!(model, agent_step!)` on Schelling model I get the error `type AgentBasedModel has no field min_to_be_happy`. I am using Agents v2.4.

**Comment by Libbum** [comment]
This is probably related to your other issue. Are you using the [correct documentation version](https://juliadynamics.github.io/Agents.jl/v2.4/examples/schelling/)?

**Comment by sbacelar** [comment]
No but I am not using the documentation to run the file. I am using the file after cloning the repository.

**Comment by Datseris** [comment]
It doesn't make sense to use the files of the `master` branch (which is what you get after you clone) and use the stable version of Agents.jl. You need to decide: either use the master version of Agents and use the example files of the master version, or use the stable version and use the examples of the stable version.

I know **guaranteed** that the examples work with their appropriate versions, because the online docs are automatically generated by running the examples. Thus, there is no way there is an actual issue here.
