### ISSUE TITLE
Interacting_pairs with different types of agents

### ISSUE THREAD

**Issue by omarbetancourt** [JuliaDynamics/Agents.jl#252]
Hello,

New to Julia and Agents.jl.

I would like to know how to use Interacting_pairs with only agents with different types.

e.g. wolves and sheep interact only. No sheep with sheep or wolves with wolves

Thanks!
- Omar B

**Comment by Libbum** [comment]
Thanks for your interest Omar. Mixed models are not as supported as single agent ones just yet, so this is not as streamlined as it perhaps could be. The solution though is to write your own set of schedulers.

```julia
function wolves_only(model::ABM{A,S,F,P}) where {A,S,F,P}
    [a.id for a in allagents(model) if typeof(a) <: Wolf]
end
```
then call

```julia
wolf_pairs = interacting_pairs(model, r, :scheduler; scheduler = wolves_only)
```
Of course you'll need one for `Sheep` too. If this pattern is something others need as well, we'll consider integrating something like this in a future version.

Let me know if that works for you.

**Comment by Libbum** [comment]
Oh. Sorry I have completely misread your question. Give me a bit to consider what you need.

**Comment by Datseris** [comment]
This is too easy to be done manually in my opinion, and thus there is no reason to "support" it directly from Agents.jl.

1. Iterate over the agents of the model. let `a` current agent.
2. For each agent call `sn = space_neigbhors`.
3. For each agent in `sn` check if the type is appropriate i.e. if `a isa Sheep` check if `s isa Wolf`, and vice versa.
4. If 3 is false, add a `continue` statement to the if clause. If not do your interaction.


full exmaple:

```julia

for a in allagents(model)
    sn = space_neighbors(a, ...)
    for s in sn
        if a isa Sheep && s isa Wolf
            # sheep wolf interaction
        elseif a isa Wolf && s isa Sheep
            # wolf sheep interaction
        else
            continue
        end
    end
end
```

**Comment by Libbum** [comment]
Ah, well, I just finished a general implementation, but got pulled into a meeting before pushing it up.

I'll do that now, take a look and see if it makes sense to incorporate or not.

**Comment by Datseris** [comment]
You can open a PR if you have it. I just felt it didn't deserve dev time... :D

**Comment by Libbum** [comment]
Omar: if you want to use this for the moment you'll need to be tracking master, by `add Agents#master`. We won't release v3.1 for a while, since this it the only addition so far.

Or, you can just sneakily copy [this method](https://github.com/JuliaDynamics/Agents.jl/blob/ab82ab80618688823006b9e9fb7b78a5661cf9d7/src/core/continuous_space.jl#L427-L440) into your current code.

**Comment by omarbetancourt** [comment]
Great! Thanks so much for implementing this!

Another neat thing to do is to call all neighbors of the same type. Similar to :all in interacting_pairs except only calling similar type.

e.g. sheep calling all other neighboring sheep and wolves calling all other neighboring wolves .

**Comment by Datseris** [comment]
But it requires literally only 5 lines of code to do these things:

```
for a in allagents(model)
t1 = typeof(a)
sn = space_neighbors(a)
for s in sn
s isa t1 || continue # ensures only same type.
```

I think these questions come more from the lack of Julia knowledge. I don't think it is reasonable to add a function into Agents.jl for every possible 5-line combination a user might need.

**Comment by Libbum** [comment]
Jump on #dynamics-bridged in the [julialang slack](https://slackinvite.julialang.org/). We can help you get up to speed there.

**Comment by omarbetancourt** [comment]
> But it requires literally only 5 lines of code to do these things:
> 
> ```
> for a in allagents(model)
> t1 = typeof(a)
> sn = space_neighbors(a)
> for s in sn
> s isa t1 || continue # ensures only same type.
> ```
> 
> I think these questions come more from the lack of Julia knowledge. I don't think it is reasonable to add a function into Agents.jl for every possible 5-line combination a user might need.

Yes, this could be the case that I'm not too familiar with Julia just yet. Especially coming from NetLogo, the only other agent-based framework I've used, where there's a bunch of primitives for each of these 5-line combinations.

**Comment by Datseris** [comment]
I have to admit I am only vaguely familiar with NetLogo, having used it only once in my bachelor years, several years ago. And I would never use it as a scientist, because it makes 0 sense to use a custom scripting software _along_ with another programming language for data analysis and plotting.

But If I interpret your words correctly, then the "primitives" of Agents.jl are true primitives: as I've demonstrated, pretty much any conceivable scenario can be created in very few lines of code by combining very basic components (which I would call primitives): iterating over agents, get neighboring agents, etc. The combination of these primitives, I wouldn't call primitives: they are already custom functions.

This design might feel different, but I truly believe it is more powerful. At least my mentality as software developer is "Give power to the user". We trust our users are smart, and given the right fundamental tools they can definitely achieve anything. On the other hand, expecting all combinations to come from the package is ineffective for these reasons:

1. A small developer team can't possibly imagine all combinations.
2. Maintaining and debugging 1000s of combinations is a nightmare.

As Tim said, if you want to ask short-n'-quick questions, join our Julia slack!

**Comment by omarbetancourt** [comment]
You're right. NetLogo's "primitives" are mostly functions. I believe using Julia is the way to go as you mentioned so that I can create my own custom functions and not be confined with what other's have only thought of. 

I'm looking forward to learning more about Julia and using Agents.jl for graduate school, which I'll be starting this fall. I know it will take me a bit to get through but that's what the summer's for! I'm kind of doing a "learn as you go" approach, trying to replicate some ABM papers for now.

I'll be definitely seeing you guys in Julia slack. 

Thanks!
