### ISSUE TITLE
Agent memory of historic values

### ISSUE THREAD

**Issue by fbanning** [JuliaDynamics/Agents.jl#262]
I was wondering if it's possible for an agent to remember a historic value of their own variables.
Consider the following:

``` julia
mutable struct MyAgent <: AbstractAgent
    id::Int
    money::Float64
end

#build some model around this
#insert fancy model code here
#such model, much wow
```

Assume the following model dynamics:
Agents spend some of their money at each step of the model.
How much they spend depends on how much they have available to them in comparison to last step.

Now I'd imagine something like this:

(**Careful: Pseudo-code incoming**)
``` julia
function agent_step!(agent, model)
    last_money = get_historic_values(; agent = agent.id, variable = money, step = current_step - 1) # returns value that agent.money had at the end of the previous step
    if agent.money >= last_money
        # do things
    else
        # do nothing
end
```

I'm wondering if it's possible for an Agent to have knowledge/memory of their own history, e.g. how much money they owned at the end of the last model step. Is that something that's easily possible? Did I miss some functionality?

Probably the most straight-forward solution that comes to my mind would be to introduce helper variables to store historic values. For example I could include `money_history::Array{Float64,1}` in the MyAgent struct. At the end of every model step, I could then push the current value of `agent.money` to `agent.money_history`.
Now personally I would prefer to keep agent variables clear from such "helpers". I would love to have a better way for agents to act according to their past.

**Comment by Libbum** [comment]
At present, we'd certainly implement something like this as an explicit history within the agent struct like you suggest with `money_history::Array{Float64,1}`. It makes the most sense to be there in terms of performance.

The next best place (currently) would be to store this in the model. That adds complexity (still in user space), since you'd need to add `money_history::Dict{Int,Vector{Float64}}` or similar. To use this in `agent_step!` would require users to pull this data out of the model solely as an abstraction from what I understand. 

Finally, we could store the history in the DataFrame exported from `run!`. This however would break the low-level API, since `step!` could no longer be used consistently across all model implementations.

Is there any reason other than 'the feeling of keeping things clean' to not store this data in the agent struct?

**Comment by fbanning** [comment]
Thank you for your answer. I think you're correct with respect to all your remarks.

> Is there any reason other than 'the feeling of keeping things clean' to not store this data in the agent struct?

I guess not. It was more of an intrigued inquiry than a real problem. I was just interested in hearing if I have missed some functionality or if the solution I thought of was suboptimal in any sense.

**Comment by Libbum** [comment]
No worries. We can leave this issue open for some of the other maintainers to chime in if they happen to have an alternate idea.

**Comment by Datseris** [comment]
> For example I could include `money_history::Array{Float64,1}` in the `MyAgent` struct. At the end of every model step, I could then push the current value of `agent.money` to `agent.money_history`.
Now personally I would prefer to keep agent variables clear from such "helpers". I would love to have a better way for agents to act according to their past.

I don't believe that any other solution besides this would be "cleaner". Implementing "history" from within the Agents.jl seems overkill, given how simple it is to be done on the user side. If done from Agents.jl side, it would have strongly negative impact on both performance, but most importantly code complexity, introducing a lot of boilerplate code and potential bugs. And then you have data collection problems as well. 

In my eyes, we shouldn't consider this issue open, simply because its solution should exist on the user side. (i.e. in the Agent struct). Besides you can even data collect this history if you keep things on the Agent structu.

**Comment by Libbum** [comment]
Agreed - just looking for a sanity check of my logic :smile:
