### ISSUE TITLE
Allow mutable graph spaces (support add_vertex! and rem_vertex!)

### ISSUE THREAD

**Issue by yanyuan-wang** [JuliaDynamics/Agents.jl#264]
Hi there, I used ABM with the `step!` function for simulation, but I found that even if some agents were killed in some steps, the graph in the space did not update. I verified this by calculating the vertices of the network using `nv(model.space.graph)`, and it seems that the output is corresponding to the beginning state of the simulation . Does anyone know why this happened? And I am wondering how can I get to know the properties of the network in each step if I cannot make use of `model.space.graph`? Thanks for your time in advance!

**Comment by Datseris** [comment]
Hi, 

> the graph in the space did not update

Please explain what this means, or better yet explain what you'd expect to happen. The underlying graph is immutable, but we do change the "container vectors" (i.e. there is an *independent structure* that counts how many agents are at each node of the graph, and that changes).

**Comment by yanyuan-wang** [comment]
Hi, thanks for your comments.

I want to calculate the centrality using `degree_centrality` for each agent in each step, so when I tried to use the `model.space.graph`, but the results were exactly the same in each step even if some agents were removed or added to the space. 

And I also tried to update the graph using `add_vertex!` and `rem_vertex!` in each step, but it was really hard to trace the vertices as the function `rem_vertex!` will swap the vertex to be removed with an equivalent one for performance reason. Could you give me some suggestions?
 
By the way, could you tell me more about the _independent structure_? Or where can I get to know more about it?

**Comment by Datseris** [comment]
> By the way, could you tell me more about the independent structure? Or where can I get to know more about it?

This is just a vector of Vectors of IDs, which keeps track of which agents are in which node. It is in the source code of `GraphSpace`.

---

I now see what you want, and this is a new feature: you want to be able to mutate the underlying graph *during* model evolution. This is currently not supported. To support this, one has to extend the methods `add_vertex!, rem_vertex!` for `GraphSpace`. These methods need to modify both the actual graph, but also the underlying `agents_positions` vector: https://github.com/JuliaDynamics/Agents.jl/blob/master/src/core/discrete_space.jl#L28

This is *not* hard I believe, because in principle you just have to remove the `n`-th entry of `agents_positions`, when you want to remove the `n` vertex. 

But it will require A LOT of testing (to cover edge cases and stuff).

**Comment by Datseris** [comment]
In progress in https://github.com/JuliaDynamics/Agents.jl/pull/326  but I don't have the necessary LightGraphs.jl expertise to finish that PR.

**Comment by Libbum** [comment]
I'd be in the same position. Could dig deeper, but that's a time-based problem.
