### ISSUE TITLE
Possible issue when collecting data of model properties of type Vector

### ISSUE THREAD

**Issue by mperhez** [JuliaDynamics/Agents.jl#273]
A property of type ``Vector`` is defined in the model: ``props = Dict(:prop1=>Vector{Int64}())``, during the simulation this Vector is filled within the ``agent_step!`` function. After data collection, looking at the model data collected for step 1, the state of ``prop1`` does not match the state as printed with ``@show`` during simulation.  If the length of the vector is stored as a property, this value is correctly collected at the end.

**Comment by Libbum** [comment]
Hi Marco. A small example would help us to figure out what's happening here. Data is collected after agent and model steps. Perhaps something is changed after the `@show` but before the save?

**Comment by Datseris** [comment]
As Tim said, data collection happens **after** both all agents have activated as well as the model step function has been called. This is illustrated in the source code of `run!`:
```julia
    while until(s, n, model)
        if should_we_collect(s, model, when)
            collect_agent_data!(df_agent, model, adata, s)
        end
        if should_we_collect(s, model, when_model)
            collect_model_data!(df_model, model, mdata, s)
        end
        step!(model, agent_step!, model_step!, 1)
        s += 1
    end
```
(here the datacollection is before `step!` simply so that step 0 is included)

This means that unless you call your `@show` method *after* all stepping is done, what `@show` shows you might be irrelevant.
Furthermore `run!` doesn't distinguish the actual type of the value. There is no different handling if a property is some number or some vector. However be aware that vectors are **mutable** things. This means the following:
```julia
julia> a = [] # initialization of data collection
Any[]

julia> x = [1, 2] # first step, property `x` is altered
2-element Array{Int64,1}:
 1
 2

julia> push!(a, x) # property x is data collected
1-element Array{Any,1}:
 [1, 2]

julia> push!(x, 3) # property x is altered at step 2
3-element Array{Int64,1}:
 1
 2
 3

julia> push!(a, x) # property x is data collected 
2-element Array{Any,1}:
 [1, 2, 3]
 [1, 2, 3]
```
So if you are mutating the same vector in place, the data collection will have the same entry in every step... You might e.g. be "clearing" `x` at the model step.

At the moment it is unlikely that it is truly an issue of Agents.jl so please do provide us with a MWE that shows otherwise.

**Comment by mperhez** [comment]
Thanks Tim and George for your prompt reply.  Yes I am mutating the same vector in place at every step and I've  moved the updating code to the ``model_step`` function to avoid potential race conditions. I think it has to do with the mutable nature of vectors as you explained. See a short example attached over your ``predator_prey.jl`` code (I changed the extension as apparently .jl is not supported for the attachment). Many thanks,

[predator_prey.txt](https://github.com/JuliaDynamics/Agents.jl/files/5053397/predator_prey.txt)

**Comment by Datseris** [comment]
No problem. Notice that you can replace the model `prop1` each time you want to "refresh" the vector (so that model data collection doesn't show the same thing all the time).

Or, you can also write your own low-level data collection loop that copies the `prop1` each time it data collects it. I don't think it is reasonable for us to by default copy everything when it is data collected, because of performance reasons.

**Comment by mperhez** [comment]
Thanks, problem solved by replacing the entire vector at every step as you suggested.
