### ISSUE TITLE
Continuous space initialization allows extend dimension mismatch

### ISSUE THREAD

**Issue by hbsmith** [JuliaDynamics/Agents.jl#287]
Currently there's no check to see if `length(extend) == D` for `ContinuousSpace`.

So users can do weird things like this:
```
ContinuousSpace(2, extend=(1,2,3,4))
ContinuousSpace(2, extend=())
```

You can even make extend some other types which don't make sense:
```
ContinuousSpace(2, extend="woohoo")
ContinuousSpace(1, extend=[[0,1,3]])
ContinuousSpace(1, extend=0)
```

The user should probably be alerted to any problematic argument definition during initialization.

**Comment by Libbum** [comment]
Thanks for alerting us to these problems! This one should be a quick fix. There were discussions around definition checks we had with `add_agent!` for example&mdash;we allow users to overwrite agent IDs without warning, so that the user can mutate their initialization freely.

Space on the other hand (especially `ContinuousSpace`) is an entity that can only be invoked once per model. Any of the suggestions you've made here will ultimately fail when the model is stepped; but I agree, it's better to return an assertion error during initialization for this.
