### ISSUE TITLE
[Help] Create continuous space boundaries and checks

### ISSUE THREAD

**Issue by MFaisalZaki** [JuliaDynamics/Agents.jl#293]
Hello, I was checking and trying to create a boundary for a continuous space using static agents. However, the problem is that I can't achieve this, So how can I do it effectively.

Thanks a lot.

**Comment by Datseris** [comment]
Closing in favor of https://github.com/JuliaDynamics/Agents.jl/issues/277

**Comment by Libbum** [comment]
Can you elaborate a bit on what you would expect for such a boundary?

You can use [`extend`](https://juliadynamics.github.io/Agents.jl/stable/tutorial/#Agents.ContinuousSpace) to define how large your space would be.

`space = ContinuousSpace(2, extend=(15.0, 2.0))`
Would give you a space that is 15 units long in `x` and 2 units tall in `y`. 

Since you state your agents are static, I guess that's all you'd need?

(otherwise, as @Datseris has already linked to, we have an obstacles issue tracking already)
