### ISSUE TITLE
Move GridSpace to a Julia Array format

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#296]

**Comment by Datseris** [comment]
My idea for this is as follows:

Instead of having a network as the underlying structure, we have a dedicated `GridSpace` type that contains:

* An n-dimensional Julia array `S` (for space) with element type `Vector{Int}`
* A boolean field `periodic`
* A boolean field `moore`

Then, when an agent moves, the implementation is similar with what we do now: we first find the appropriate entry in `S` by *directly* accessing it with the agent's original position: `S[agent.pos...]`. We remove the agent id from this entry of `S`. We add the agent to the new entry of `S` by pushing `push!(S[new_pos...], agent.id)`.

Finding neighbors is as simple as collecting the appropriate entries around the agent position. However, we can do clever programming to allow this to be possible for `n`-dimensional discrete space. We have infact already done something similar in our TimeseriesPrediction.jl work. Here: https://github.com/JuliaDynamics/TimeseriesPrediction.jl/blob/master/src/spatiotemporalembedding.jl#L246 we have written performant code that allows us to do such things in arbitrary dimensions.

**Comment by Datseris** [comment]
I'll tell you what: we can re-use work of TimeseriesPrediction.jl here. But TimeseriesPrediction.jl is quite complicated in its source, and I am the only one familiar with it. I think I should do this part of `DiscreteSpace`. Then either @kavir1698 or @Libbum can do the continuous space.

We should do this version first, because I have the idea that continuous space can have a `DiscreteSpace` as its field. Then, it can simply be used internally by continuous space: find neighbors first finds the neighboring cells (called "compartments") and then simply refines the collected result by filtering according to the given distance metric.

**Comment by Libbum** [comment]
Closed via #311.
