### ISSUE TITLE
The methods of the step! function

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#38]
Hi there,

in the process of redesigning and vastly simplifying the API, we have to face the current `step!` function. The problem from my eyes, is that this function is unwieldy. 

Not only it has 10 methods, but it even does multiple dispatch in 3 different argument positions. Something tells me hat things will be much simpler if we just separate many of its methods into different functions. What was especially confusing for me was the story with the aggregators, propagators, and all that jazz. To my understanding, `step!` has four (!!!) different functionalities:

1. Normal stepping.
2. Collecting agent properties
3. Appying aggregators
4. Doing whatever `propagg` does (I have not understood this at all.

(also, it seems that numbers 2, 3 and 4 **cannot** happen at the same time)

In my eyes, this is way too much stuff that are done by a single function name. A function should do one, and only one thing. This keeps things clear, and most importantly **easy to learn**.

@kavir1698 , can you please give some input here, on how we can simplify this approach?

My suggestion would be to have `step!`, `collect!`, `aggregate!`, `propaggate!` ( still don't know what this is).

**Comment by Datseris** [comment]
Or, we can take a page out of the book of DifferentialEquations.jl and DynamicalSystems.jl and create a `Stepper` object. This object will be doing the stepping, and _it_ will be passed around to the 3 data collection functions.

I like this idea _a lot_, because it removes the unnecessary dispatch on `model_step!` as well!

**Comment by kavir1698** [comment]
Hello,

I don’t think that a function that does many different things is problematics. It would be similar to the `plot` function in most plotting packages, where one can only pass x and y arrays, or add a ton of keyword args on top of that to modify the plot.

Similarly, separating the arguments of the `step!` function to separate functions does not change how much a user should learn. It just makes them to write more lines of code to do the same thing.

Perhaps, making most of the arguments as keyword arguments, and better explaining them in the docs is enough to make things easier.

About the `propagg`. It is a dictionary of whose keys are “properties” and values “aggregators”. So basically, one can apply different aggregators to different agent or model fields.

I do not know how the stepper object works in those packages. I should check them out.

From: George Datseris
Sent: Wednesday, October 23, 2019 12:58 AM
To: JuliaDynamics/Agents.jl
Cc: Ali R. Vahdati; Mention
Subject: [JuliaDynamics/Agents.jl] The methods of the step! function (#38)

Hi there,
in the process of redesigning and vastly simplifying the API, we have to face the current step! function. The problem from my eyes, is that this function is unwieldy.
Not only it has 10 methods, but it even does multiple dispatch in 3 different argument positions. Something tells me hat things will be much simpler if we just separate many of its methods into different functions. What was especially confusing for me was the story with the aggregators, propagators, and all that jazz. To my understanding, step! has four (!!!) different functionalities:
1. Normal stepping.
2. Collecting agent properties
3. Appying aggregators
4. Doing whatever propagg does (I have not understood this at all.
(also, it seems that numbers 2, 3 and 4 cannot happen at the same time)
In my eyes, this is way too much stuff that be are done by a single function name. A function should do one, and only one thing. This keeps things clear, and most importantly easy to learn.
@kavir1698 , can you please give some input here, on how we can simplify this approach?
My suggestion would be to have step!, collect!, aggregate!, propaggate! ( still don't know what this is).

**Comment by Datseris** [comment]
> I don’t think that a function that does many different things is problematics. It would be similar to the `plot` function in most plotting packages, where one can only pass x and y arrays, or add a ton of keyword args on top of that to modify the plot.

I would suggest to reflect a bit more here, and think about this a bit more to maybe have a more broad view for future APIs. A plotting function is a good example, because, even though it has 100s of keyword arguments, it always does one thing: it **plots** some values `x` versus some values `y`. The keywords only control how is this thing looks like and never affect the core functionality. 

In our case, `step!` does not do one thing. I personally consider evolving the ABM, collecting additional data and processing data three different things. Maybe having this `Stepper` structure is too complicated, true. But please consider more my above comments in general, not specifically for Agents.jl. 

I find your suggestion of making _all_ of these extra arguments keyword arguments appealing, although this may have some minor performance impact. I am not sure how to measure performances but once I open a PR I think you will be able to help.

**Comment by kavir1698** [comment]
Thank you for your response. I agree with your logic that we should define new functions when they do something different. Nevertheless, the line that separates different functionalities is not that sharp.

Taking the plotting example, putting data points on the screen is a different functionality than changing the size of the plot, the range of the axes, and log-transforming the axes, for example. These other functionalities modify the representation of the data.

The extra arguments of the `step!` function also modify the `DataFrame` object that the simplest `step!` function would return. The modifications are in the form of aggregation of data.

Another point is that data aggregation occurs at every step of the simulation. Thus, we do not first build a huge DataFrame, and then aggregate the data and return a smaller DataFrame. Instead, for each step of a simulation, we gather the data, aggregate them, and then add the aggregated data to the find DataFrame. I am not sure how this would work if the aggregation function was separate from the step function.

I should say, I am not insisting that all these functionalities should be arguments of the `step!` function. I am only evaluating the situation from my perspective.

I did not know that keyword arguments have an impact on performance. But the since the biggest bottle in most simulations is the actual simulation, I doubt that making the arguments keyword arguments affects the performance considerably.

**Comment by Datseris** [comment]
I think we are making progress, and it seems keyword arguments to `step!` is the way to go. 

Another comment: seems to me that propagators superseeds aggregators, that is, anything that can be done with aggregators can be done with propagators, along with more stuff. Shouldn't we ditch aggregators alltogether? The documentation is not very clear in exactly what the aggregators and propagators do and in *exactly* what form they are expected (for example, should the aggregator vector have same length as the properties vector?). Can you please explain them in more detail so that I can document them further, and simplify the code if possible?

(by the way, there is the branch `One_space_to_rule_them_all`, which is a re-work of the API based on the discussions we have been having in the various issues. You can have a look from time to time. I am updating the `tutorial.md` as I go along.)

**Comment by kavir1698** [comment]
> anything that can be done with aggregators can be done with propagators, along with more stuff. Shouldn't we ditch aggregators alltogether?

Yes, they do the same thing. It can be helpful to only keep the propagators for making things simpler.

Aggregators is a list of functions each of which will be applied to each element of the properties vector. The two vectors do not have to have the same length. The proaggators is a dictionary (keys are properties and values are functions) that gives more control so that one can limit which aggregator functions are applied to which properties.

Thank you for working on these issues. I will check the branch and write any comments I might have.
