### ISSUE TITLE
Pathfinding

### ISSUE THREAD

**Issue by AayushSabharwal** [JuliaDynamics/Agents.jl#402]
**Is your feature request related to a problem? Please describe.**
Currently grid space doesn't store any properties about the grid. This could be useful for simulating things like different types of land, walkable and unwalkable terrain, or the grass in predator-prey. Instead of having agents represent tile properties, they should be intrinsic to the space itself. This can also enable having pathfinding algorithms using either A* or LightGraphs.jl, and allow for travel costs to vary with the grid cell. I've been thinking of making an improved predator-prey simulation with these features, and maybe some more. Additionally, visualization support in InteractiveDynamics.jl can be improved by automatically plotting the background tiles first and the agents on top, instead of having to rely on a scheduler.

**Describe the solution you'd like**
Each grid cell can have a struct property. Possibly have an additional `_step!` function for the grid.

**Describe alternatives you've considered**
My primary motive for this is the possibility of adding pathfinding to grid space, and simplifying how such properties and interactions work. The other alternative I've thought of is simply having a model property to do this, although semantically this seems more of a space-specific thing. I am welcome to other suggestions.

**Comment by Libbum** [comment]
Take a look at [Daisyworld_matrix.jl](https://github.com/JuliaDynamics/Agents.jl/blob/master/examples/daisyworld_matrix.jl), this is how I initially built it, with temperature as a model property. It was changed in #263, mostly to showcase some more multi-agent systems, although the matrix version is more performant.

There are a few things that spring to mind initially:

> Additionally, visualization support in InteractiveDynamics.jl can be improved by automatically plotting the background tiles first and the agents on top, instead of having to rely on a scheduler.

Not really true in terms of complexity. The scheduler option allows you to make sure the things you want to be plotted will be plotted, and the way its organised now (for wolf-sheep at least) is one line.
Sure, if the only space property you have is grass, then it's trivial to print the space property first. What if you have grass and water? A method, essentially the same as the scheduler call would need to be provided. Then, because properties have been separated from the model to the space, rather than one source of truth, there is two.

This happens already in [Battle Royale](https://github.com/JuliaDynamics/Agents.jl/blob/master/examples/battle.jl). We essentially overload the space to do something that it's not. It's a concept that's possible, but perhaps in the end not entirely practical.

> My primary motive for this is the possibility of adding pathfinding to grid space

This would of course be nice. Generally, the way that we've added features such as this recently is started with an example, made in the context of some of our `Ecosystem Integration` examples on the docs. The story starting at #264 is the best case. We started implementing a whole new structure in #324 that ended up, after consideration, to be almost non-nonsensical and irrelevant. Instead, two new methods were introduced and one example added: case closed. 

> simply having a model property to do this, although semantically this seems more of a space-specific thing

**Using a model property as a starting point in an example is the best way forward here.** It means we don't need to do any breaking changes to the current framework. Then, once we see how it fits, we consider if it makes the most sense to move it to a space property, or something else entirely.

Right now, for example, I'd think that having path-finding operate on `ContinuousSpace` would also be needed, so farming out additional properties to the space would mean at least two separate implementations. Maybe that needs to be done, but also equally true is that we just need a few functions that can operate outside of the spatial structure.

Feel free to present some starting work in a new PR and show how some of the considerations you've put forward here would make the most sense.

**Comment by AayushSabharwal** [comment]
I see your point about visualization not being any easier. I think I've been going about this in reverse. I was looking for pathfinding, and grid properties seemed the appropriate way to do it, since agents as landscape components are a bit hard to keep track of. Might have been better to open an issue for pathfinding, and see the solutions that emerge there.

After a bit of thinking, I have some more ideas specifically for pathfinding in `GridSpace`. One option could be maintaining a graph between landscape agents, similar to the graph between students in the `LightGraphs.jl` example. Another could be similar to the matrix daisyworld you highlighted, where a model property is used as map data.

Additionally, `ContinuousSpace` would probably require some special consideration, since obstacles could be pretty complex and discretisation of the space might not always be the best solution. There already seems to be some related discussion in https://github.com/JuliaDynamics/Agents.jl/issues/277. A solution like the accepted answer for [this question](https://gamedev.stackexchange.com/questions/132398/pathfinding-in-non-quantized-space) in stackexchange might be something to look into.

**Comment by Libbum** [comment]
Start wherever you can and let's build on it. Easiest first&mdash;this will no doubt be a big change to satisfy everything. It's possible we will need to implement more than one algorithm.

The stack exchange solution looks cool, but we may be able to do some tricks since `ContinuousSpace` is compartmentalised on a grid under the hood for quick nearest neighbor searching. Perhaps we can therefore get away with a grid/graph based method anyway...

---

https://github.com/JuliaRobotics/EnhancedGJK.jl

I've been looking into this as perhaps one method. Solutions like this will also need #155 to be done, so if we were to choose GJK for example, it would make sense to build off of `GeometryTypes`.

https://github.com/JuliaGeometry/Meshes.jl

Also seems like a project to track, although it looks a little too young for the moment to be building upon.

**Comment by AayushSabharwal** [comment]
Grid based seems to be the place to start. I'll think about some of the semantics of how pathfinding should interact with agents, and then make a PR as a starting point.

**Comment by AayushSabharwal** [comment]
The A* algorithm needs heaps. Currently, I'll add `DataStructures.jl` as a dependency, although this may be a good place for https://github.com/JuliaDynamics/Agents.jl/issues/397

**Comment by AayushSabharwal** [comment]
Started work in https://github.com/JuliaDynamics/Agents.jl/pull/405

**Comment by Libbum** [comment]
#447 has implemented most of this. Some outstanding discussions have been moved to appropriate open issues.
