### ISSUE TITLE
Plotting the space

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#443]
We need to modify `abm_plot` and company, to allow plotting an aspect of the space/model _before_ plotting the agents. This will be useful in E.g. porting OSM to Makie, or e.g. in the movie @Libbum pasted in Pathfinding, with runners running along a mountain range.

The difficulty for me at the moment is how to make the interface. If it is a static plot, that is easy. We have a single function `plot_model!(ax, model)` that plots the model on the axis that hte agents will leave, with whatever plotting commands the user needs. 

But what if there is a need to also animate the "model" / "space"? Then I'm not sure... I guess the simplest way to do this would be via only allowing a heatmap as the animatable aspect because otherwise I'm not sure how we can cover every case.

**Comment by Libbum** [comment]
Yeah, this would be nice. Although I kind of lucked out on the heatmap thing. I thought it'd plot over the top of the agents, but it didn't.
```julia
f, abmstepper = abm_plot(model; as = 10)
ax = contents(f[1, 1])[1]
heatmap!(ax, heightmap)
limits!(ax, 0, 400, 0, 500)
hidedecorations!(ax)

record(f, "runners.mp4", 1:400; framerate = 25) do i
    Agents.step!(abmstepper, model, agent_step!, dummystep, 1)
end
```

My Makie-foo is not as good as yours yet. So why this works is still a little magic to me. But maybe it helps the design of this process.

**Comment by Libbum** [comment]
Something else we'll need to consider here is the backend we use for things when we're plotting the space.
The example in Pathfinding I used GLMakie since I was prototyping. When I use CairoMakie, since it's actually converting each value of the map it a vector based representation it takes forever to plot & looks pretty bad. Also, the agents do not show up.

(Same plot with CairoMakie)

https://user-images.githubusercontent.com/3059508/109140768-3f253900-775d-11eb-85fe-234730f49d4f.mp4
