### ISSUE TITLE
Consider making modules for specific components to decrease namespace bloat

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/Agents.jl#458]
@Libbum , I have been contemplating over this, and the FMP pull request as well, and the exported names we have are becoming quite a lot... Should we consider submodules? `Pathfinding.names`, `FMP.names`, `OSM.names` ? Because I am thinking that many names become hard to understand without context, which is e.g. why we append `osm_` to all names from open street map. If we specify by module, this appending to names is not necessary anymore.

_Originally posted by @Datseris in https://github.com/JuliaDynamics/Agents.jl/issues/447#issuecomment-800108848_

**Comment by AayushSabharwal** [comment]
Since pathfinding is completely self-contained, it could all be put behind something like `Agents.Pathfinding` if necessary without impacting anything else.

**Comment by Datseris** [comment]
Same goes for the Forced Motion Planning although it isn't that large of a functionality. Perhaps though I could put in there the `elastic_collision` stuff as well.

**Comment by fbanning** [comment]
If that's of any concern, I would personally very much like this to happen. Function names are indeed starting to feel a bit cumbersome wrt what to prepend and this is likely to grow further on. Another example for this would be the newly renamed `schedule_fastest` functions. Grouping these in submodules could also help through ergonomic tab completion, e.g. `Sc <TAB> .f <TAB>` for `Schedulers.fastest`, but that might just be a personal preference.

This has to be implemented with care though, especially regarding coherence in naming. Currently we have the type and its related constructor function [`ContinuousSpace`](https://juliadynamics.github.io/Agents.jl/stable/api/#Continuous-spaces) which might overlap with a sensible name for the [Continuous space exclusives](https://juliadynamics.github.io/Agents.jl/stable/api/#Continuous-space-exclusives) that would intuitively go into an own submodule called `ContinuousSpace`.

Personally I think having `ContinuousSpace.ContinuousSpace(...)` might be a bit unwieldy and frankly a bit confusing as well. Possibly name changes for the constructor functions would be sensible (something like `ContinuousSpace.create(...)`) so that they can be easily distinguished from the submodules themselves.  
Just my two cents and maybe something to keep in mind when deciding to implement this.

**Comment by Libbum** [comment]
Yep. We're thinking that spaces will remain part of the main module for now. At 5.0 that may be revisited. 

Schedulers, as you say - that could work, but it's also more breaking than we'd like for 4.2. Most of the stuff we'd cover for now in this PR is the new things like pathfinding.

**Comment by Datseris** [comment]
I personally stand that spaces must absolutely be accessible as direct level name space. They are not self-contained functionality but are tied with the entire API. Where should the function `move_agent!` be if we make spaces sub-modules? I really don't like this and I truly hope it will not happen at 5.0.

---

Moving the schedulers is a great idea. We just had a PR renaming all schedulers to start with `schedule_` hahaha , time to change all this `schedule_` to `Schedule.` once again, sorry @rht

**Comment by rht** [comment]
> Moving the schedulers is a great idea. We just had a PR renaming all schedulers to start with schedule_ hahaha , time to change all this schedule_ to Schedule. once again, sorry @rht

At least those `schedule_` are much easier to grep to be replaced with `Schedule.` than without.
