### ISSUE TITLE
Parallel paramscan

### ISSUE THREAD

**Issue by Adriankhl** [JuliaDynamics/Agents.jl#481]
If I understand it correctly, it is not possible to parallelize paramscan, especially after (https://github.com/JuliaDynamics/Agents.jl/pull/476).

May I ask why this is the case? It seems like it is strict forward to implement with something like parallel map, and it is really useful to speedup big run.

**Comment by Libbum** [comment]
You can certainly distribute paramscan with a `pmap` if that's something you need. #476 removed the replication capability (run multiple versions of the same parameter set), since that never really made sense.

This is a new change though, and we have yet to release this change (its only on master). If you have a use case, please provide an example of what you're interested in doing and we can either guide you to a solution with the new syntax; or modify these recent changes to accommodate.

**Comment by Datseris** [comment]
> If I understand it correctly, it is not possible to parallelize paramscan, especially after (#476).

Let's be a bit precise here because what was happening was not what you currently have in mind.

The old `paramscan` was doing something "weird": when `replicates > 0` it was running a `deepcopy` of the model, for the exact same parameter combinations, many times in parallel. With Agents.jl 4.1, where the random number generation became an internal property of the model, this became somewhat nonsensical due to the deep copying. Unfrotuantely we did not realize this when releasing 4.1 so `paramscan` in 4.1 is just a "bad function".

Furthermore, I _personally_ believe it does not make sense to do at the same time a parameter scanning _and_ an ensemble simulation and it is better to keep these two processes separated. I might be wrong.

Regardless, with the new design currently on master, **it is in fact indeed possible to truly parallelize `paramscan` over different parameters**. This is because `paramscan` generates a _new model_ for each parameter combination.  This is clear from these lines: https://github.com/JuliaDynamics/Agents.jl/blob/master/src/simulations/paramscan.jl#L85-L86

@Adriankhl are you perhaps interested to look in the source code here https://github.com/JuliaDynamics/Agents.jl/blob/master/src/simulations/ensemblerun.jl and make a PR that offers the same parallization for `paramscan` based on `pmap`? I believe it is an easy contribution.

**Comment by Adriankhl** [comment]
> Furthermore, I _personally_ believe that parameter scanning and ensemble simulations should be separate processes. I might be wrong.

I have done such things in my project (multiple parameter scanning and multiple runs for same set of parameters) to plot relations between variables and the error bars/bands. If the random seed can also be a parameter in the scanning then it should be good.


> @Adriankhl are you perhaps interested to look in the source code here https://github.com/JuliaDynamics/Agents.jl/blob/master/src/simulations/ensemblerun.jl and make a PR that offers the same parallization for `paramscan` based on `pmap`? I believe it is an easy contribution.

Sure I can try to do that. Though I am a bit new to the julia ecosystem so it may take some time to set things up.

**Comment by Datseris** [comment]
> If the random seed can also be a parameter in the scanning then it should be good.

This is already possible. If `seed` is one of the parameters of the model initialization function, then you can provide many seeds and get many model runs.

**Comment by Libbum** [comment]
Closed in #484.
