### ISSUE TITLE
Agents don't follow OSM roadways if they are Polylines

### ISSUE THREAD

**Issue by mcamachom** [JuliaDynamics/Agents.jl#498]
Hi, I am using Agents for a research project to simulate cars moving in a city, but after downloaded the piece of OSM area I want to use, I realize that all roadways are considered as straight lines by move_along_route!. 
In this way, when I plot the map, I can see how cars don't follow the plotted streets.

Something similar ocurred in OpenStreetMapX: The function plot_map included in samples, did not take into account these polylines, so, again, tile streets did not match the plotted ones. I have substituted this part:

    for e in edges(m,g)
    info = "Edge from: $(e.src) to $(e.dst)&lt;br&gt;[information from the &lt;pre&gt;.e&lt;/pre&gt; and &lt;pre&gt;.w&lt;/pre&gt; fields] "
    flm.PolyLine(  (latlon(m,e.src), latlon(m,e.dst)), color="brown", weight=4, opacity=1).add_to(m_plot)
    end

by this:

    for e in m.roadways
        puntos=[]
        for i in 1:size(e.nodes,1)
            lla=LLA(m.nodes[e.nodes[i]],m.bounds)
            append!(puntos, [(lla.lat, lla.lon)])
        end
        flm.PolyLine(  puntos, color="brown", popup=info, weight=4, opacity=1).add_to(m_plot)
    end

and now it seems to work. 
I am saying this just in case it is someway related.

May i get some directions to help solving this?

Agents v4.2.4

**Comment by Libbum** [comment]
This is indeed a known issue from an Agents.jl point of view and is a direct consequence of the OpenStreetMapX implementation of what roads are. They are considered to be 'the connection between two intersections'. This is a false assumption, because not all road are straight lines between two points.

The long term goal for Agents.jl is to remove the dependency on OpenStreetMapX for our `OSMSpace`, since it does not accurately represent things we are interested in (like your particular case). Whilst this is on the roadmap, a solution will require a concentrated effort which, in the near term, the core developers cannot commit enough time to.

Unfortunately, I'm not aware of anything better than OpenStreetMapX in the Julia ecosystem at present either. So it looks like there's no quick fix to this issue at the moment sorry. If this is something you'd like to assist us with, the help would be appreciated.

**Comment by mcamachom** [comment]
I will take a deeper look at OpenStreetMapX to guess the effort required and I will get back to you.

Thanks for the info

**Comment by mcamachom** [comment]
Hi,

I have been taking a look to OpenStreetMapX and I am afraid that it will take a lot of time for me to write the code needed. A time I do not have now.

:(

**Comment by Libbum** [comment]
Yep, same with us. It's a fundamental rewrite :/

Rest assured, this issue is rubbing me the wrong way too, and as soon as I've got time to devote to it, I'll be working on fixing it. Will ping you once that happens.

**Comment by mcamachom** [comment]
Great, thanks.

What I have done so far is a little program that substitutes polylines in the osm with their equivalent stretches. In this way, at least, the roads are more reallistic. It a sort of preprocessor of the osm file, so OpenStreetMapX still works.
If you consider this useful, I can send the code for you to evaluate, and by chance, integrate it into Agents.

**Comment by Libbum** [comment]
Yeah, certainly that sounds like a good start! Either link to a gist or if you're feeling adventurous: try to make a draft PR and we can put it into Agents directly.

**Comment by mcamachom** [comment]
Well, this is the link to the gist:
https://gist.github.com/mcamachom/9a643c2797e53962be8b01b810bf8110

Cheers.

**Comment by Datseris** [comment]
@AayushSabharwal this is fixed on `master` due to using LightOSM.jl, right?

**Comment by AayushSabharwal** [comment]
Yeah, it is.
