### ISSUE TITLE
Agents get stuck in OpenStreetMapSpace example

### ISSUE THREAD

**Issue by fbanning** [JuliaDynamics/Agents.jl#595]
In our example for `OpenStreetMapSpace` I've observed the following situation after about 3000 steps:

![Screenshot_20220207_172811](https://user-images.githubusercontent.com/65158285/152829867-e3ac2e25-1f49-4040-8a5d-8e4f1bd647cd.png)

A big share of the agents are stuck in dead ends of our map and can't seem to find their way out.
@AayushSabharwal Could it be the case that the wayfinding algorithm is broken?

**Comment by AayushSabharwal** [comment]
It's possible. There might be an edge case for dead ends. The wayfinding algorithm was the most difficult algorithm due to the number of cases to handle, exacerbated by the fact that any position has two possible representations.

I'll try and get to this after a week, I'm absolutely swamped with work lately!

**Comment by Datseris** [comment]
No stress. This is not a blocking issue for releasing 5.0!
