### ISSUE TITLE
Filtering in `random_nearby_stuff` and `random_nearby_pos`.

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#650]
**Is your feature request related to a problem? Please describe.**

I am simulating the Daisyworld (which exists in our examples) and I am noticing that at some step of the simulation, we need to find a random nearby position that is empty. At the moment the way to do this is to collect nearby positions and then filter them.

**Describe the solution you'd like**
It would be nice if we had a function `random_nearby_position(pos, model, r, f)` that uses filtering function `f`, as in standard `Base.filter!` to skip invalid positions. And of course, same filtering extension would be added to `random_nearby_id`. 

**Describe alternatives you've considered**
The alternative allocates memory. 

By the way @AayushSabharwal have we ever benchmarked whether `rand(collect(nearby_ids(pos, model)))` is faster than `random_nearby_id(pos, model))`?

**Comment by Tortar** [comment]
I investigated why there is a difference, and the problem is that when the model is periodic the iterator for the multigrid  is not inlined, so using `@inline` before the multigrid iterator seemed to solve the problem (the timings for this benchmark becomes similar for periodic and aperiodic model) but there is a catch: trying to see if there was a performance benefit in the flocking model I noticed that there was actually a regression!! I read somewhere that forcing inlining can be indeed not good for performance, and this seems to corroborate, so, summarizing, there is nothing to do about this

**Comment by Tortar** [comment]
Forgot to add measurements.jl in the pr but pushed to main the modified example!
