### ISSUE TITLE
Different versions of `AgentBasedModel`

### ISSUE THREAD

**Issue by AayushSabharwal** [JuliaDynamics/Agents.jl#668]
@AayushSabharwal a bit off topic, but here the idea we've breafly chatted about once becomes useful: The "different versions of `AgentBasedModel` and a version for "unkillable" agents, which uses vector and hence much better performance. Would you please be so kind to open a new issue discussing this, before we forget it? There are benefits to implement this, it's clear, so let's have an issue for it in case someone has the time to do it.

_Originally posted by @Datseris in https://github.com/JuliaDynamics/Agents.jl/issues/659#issuecomment-1198490335_

We should document a required interface for `ABM`, similar to our spaces API. Adding an `AbstractABM` supertype would also be useful for dispatch.

**Comment by Datseris** [comment]
This will also allow us to have a different type, with potentially different internals, for multi agent models. I've though of a couple of internal implementations with tuples of dictionaries, and a main dictionary mapping id to inner dictionary. But first let's write down the API we'd need for `AbstractABM`.

**Comment by Datseris** [comment]
Okay, here is my list, and let's edit this list as we add more. `model` is an instance of a subtype of `AbstractABM` in the following.
- `model[id]` gives agent given id
- `model.property` gives model level property
- `model[id] = x` errors
- `model.property = x` calls `setindex!` on the property
- `model.rng`, which should be replaced to `rng(model)` gives the rng. The reason I am saying this should be replaced is because it allows separating the "get properties" interface from the "get 'internal' properties" like `rng` or `schedfuler`.
- similarly `model.scheduler` which should become `scheduler(model)` gives a default scheduler
- `agenttype(model)` returns the type(s) of agents
- `nagents(model)` returns the total number of agents
- `nextid(model)` which returns a valid unoccupied ID for making a new agent
- `seed!(modl)` is REMOVED in favor of `seed!(rng(model))`.
- `allagents(model) 

We also need the following new internal functions, as internally we currently just do `model.agents[agent.id] = agent`.
- `add_agent_to_model(agent, model)` which replaces `model.agents[agent.id] = agent`
- `remove_agent_from_model(agent, model)`
- `update_model_maxid(id, model)` which replaces `model.maxid[] < agent.id && (model.maxid[] = agent.id)`

**Comment by AayushSabharwal** [comment]
Why does the `id` need to be passed in to `update_model_maxid`? Can't it be `increment_model_maxid(model)`?

**Comment by Datseris** [comment]
So that we don't increment the internal `id` if not necessary. Same thing as how we do it now.
