### ISSUE TITLE
Bug in `agents_in_position`

### ISSUE THREAD

**Issue by MA-Ramirez** [JuliaDynamics/Agents.jl#767]
Hello, 

**Describe the bug**
It seems that `agents_in_position` is not working properly.
Instead of returning the agents in the position, it returns Base.Generator{...}

**Minimal Working Example**
```Julia
using Agents
using Random: Xoshiro

space = GridSpace((25, 25))

@agent Rabbit GridAgent{2} begin
    energy::Float64
    Δenergy::Float64
    reproduction_prob::Float64
end

function init_rabbits(; 
        total_agents = 100, 
        griddims = (20, 20),
        energy = 10.0, 
        Δenergy = 5.0, 
        reproduction_prob = 0.1,
        seed = 1234,
    )
    
    space = GridSpace(griddims)
    
    rng = Xoshiro(seed)
    
    model = AgentBasedModel(Rabbit, space; rng)
    
    for n in 1:total_agents
        add_agent!(model, energy, Δenergy, reproduction_prob)
    end
    return model
end

model = init_rabbits()

a1 = agents_in_position(model[1],model)
```

**Agents.jl version**
Agents v5.8.0

**Solution to the bug**
I looked into the code. It seems that the problem arises because a `Generator` instead of an array outputs the desired `agent`(s).
Also, there was no test for this function.
Therefore, I created a PR to fix the bug with its corresponding tests.

**Comment by Tortar** [comment]
I don't think Julia experience is of any particular importance, this is a general programming concept, additionally utilizing a function like this usually means iterating over the result, so I don't see any motivation for this change. Your second option seems much more appealing instead, I would improve the docstrings this way: `return a generator of ...`, this can be also done in all the places where generator are used!

**Comment by Tortar** [comment]
wait, even better in my opinion to just mention the returning value

**Comment by MA-Ramirez** [comment]
Probably we could change the doctring for `agents_in_position` to be similar to `nearby_positions` in the sense that it is stated that the function "returns an iterable of the agents in `position` ...."

**Comment by Tortar** [comment]
Yes, this seems good to me :-)

**Comment by Datseris** [comment]
![image](https://user-images.githubusercontent.com/19669089/224073411-fd17b3d9-f7a7-4c70-bb41-a5032604a85e.png)

There isn't any bug in the function. The function also doesn't claim to return a vector of agents. The function does as claimed, returning the agents in position. On purpose the docstring does not use anything in ticks. It has "agents" instead of `agents`. Things in ticks are Julia code and have 100% accurate and concrete meaning. Things without ticks are English words with only approximate meaning. So "agents" is any arbitrary plural of a single agent, so any collection of agents. Here this happens to be a generator. In other functions it is `Iterators.Flatten`. In others it is `Iterators.Filter`. These are not documented because it doesn't matter: they are just collections of agents and that's really the only thing necessary for the user to know to use the output. Iterating over generators, `Iterators.Flatten` or `Vector` is the same after all.

---

> Nonetheless, for an average user who is not so experienced with Julia, for the function to return Base.Generator{..........} instead of agent (as stated in the documentation) can be confusing.

That is okay. Encountering something you don't know in code can be confusing but that is normal. The solution is to learn what one does not know so one is no longer confused. The purpose of the documentation strings of Agents.jl isn't to teach generators or any other concept that is learned from learning Base Julia. The purpose of the docstrings is to teach Agents.jl.
