### ISSUE TITLE
A scheduler API

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Agents.jl#97]
At the moment we don't have a well-defined scheduler API (which is good, as it means no breaking changes), but we should have.

We should think:

* what should the scheduler function take as an input.
* what it should return.

and be consistent about it.

Then document it in the API/schedulers page so that other people can easily extend this API.

**Comment by kavir1698** [comment]
> what should the scheduler function take as an input.

The current input, model object, sounds like a reasonable choice. The activation order may depend on model properties, which are available through the model object.

> what it should return.

Here, I think it is worth it to accept various types, iterators and abstract arrays, because arrays are easier to produce for custom schedulers.

**Comment by Datseris** [comment]
I was also thinking about that. So in general what we want is an iterator over IDs. 

Whether this iterator is really an array or just an iterator is something you think we shouldn't care?

**Comment by kavir1698** [comment]
> Whether this iterator is really an array or just an iterator is something you think we shouldn't care?

Yes, I think allowing arrays in addition to iterators lowers the bar for inexperienced users to create schedulers for themselves.
